# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a561a943ccde75132a7444c5f193031561791ec435c78b71cd77746cf693f7fbb5841c2eb0db3478a249ccc4c8ddcc158c5ef26725b56e80107d138342f24abf

test:
  secret_key_base: e2f9418bc996c5d7f38ee39f5818b4891b2b8fefc4a2ffc15ff045c620edc82f85689411a0f72a442c49e65b70a60fb3fbc5e4c9c991dfa1c5d0033a81a66fcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
